// GENERATED by scripts/gen-seed.js from data/season-seed.json — DO NOT EDIT.
// Edit the JSON and re-run:  node scripts/gen-seed.js
import Foundation

enum Seed {
    static let me = MeInfo(
        name: "Dana Mercer", initials: "DM", role: "Skip",
        club: "Kamloops CC", prov: "BC", season: "Season 2025–26 · in progress",
        stats: MeStats(clubs: 12, prov: 4, games: 38, win: 68))

    static let recentStopIDs: [String] = ["kelowna", "vernon"]

    static let curlers: [Curler] = [
        Curler(id: "sam", initials: "SR", name: "Sam Reid", role: "Skip", club: "Vernon CC", prov: "BC",
               metAt: "Kelowna · Jan 2026", following: false,
               record: "21–9", win: "70%", clubs: 9, mutual: 3,
               sharedClubs: ["Kelowna", "Vernon", "+4 more"],
               form: [
                GameLine(label: "A-final · Kelowna", score: "8–5", res: "W"),
                GameLine(label: "Semi · Kelowna", score: "7–6", res: "W")
            ]),
        Curler(id: "jo", initials: "JM", name: "Jo Mara", role: "Lead · Spare", club: "In roster", prov: "BC",
               metAt: "Kelowna · Jan 2026", following: true,
               record: "15–11", win: "58%", clubs: 7, mutual: 5,
               sharedClubs: ["Kelowna", "Kamloops", "+2 more"],
               form: [
                GameLine(label: "Pool · Kelowna", score: "6–4", res: "W"),
                GameLine(label: "Tie-break · Vernon", score: "5–7", res: "L")
            ]),
        Curler(id: "dee", initials: "DT", name: "Dee Tan", role: "Lead", club: "Glenmore CC", prov: "BC",
               metAt: "Kelowna · Jan 2026", following: false,
               record: "12–10", win: "55%", clubs: 6, mutual: 2,
               sharedClubs: ["Kelowna", "Glenmore", "+1 more"],
               form: [
                GameLine(label: "Pool · Kelowna", score: "7–5", res: "W"),
                GameLine(label: "Pool · Kelowna", score: "4–8", res: "L")
            ]),
        Curler(id: "carter", initials: "BC", name: "Bryn Carter", role: "Skip", club: "Sage Valley CC", prov: "AB",
               metAt: "Kelowna · Jan 2026", following: false,
               record: "18–12", win: "60%", clubs: 8, mutual: 1,
               sharedClubs: ["Kelowna", "Calgary", "+3 more"],
               form: [
                GameLine(label: "Pool · Kelowna", score: "4–8", res: "L"),
                GameLine(label: "Final · Calgary", score: "9–7", res: "W")
            ]),
        Curler(id: "lind", initials: "EL", name: "Erik Lindqvist", role: "Third", club: "Granite City CC", prov: "MB",
               metAt: "Kelowna · Jan 2026", following: true,
               record: "24–8", win: "75%", clubs: 11, mutual: 2,
               sharedClubs: ["Kelowna", "Winnipeg", "+5 more"],
               form: [
                GameLine(label: "Pool · Kelowna", score: "7–5", res: "W"),
                GameLine(label: "Final · Winnipeg", score: "6–5", res: "W")
            ])
    ]

    static let stops: [Stop] = [
        Stop(id: "kamloops", code: "KAM", name: "Kamloops Cashspiel", club: "Kamloops Curling Club", prov: "BC",
             dates: "SAMPLE STOP", record: "—", here: true, x: 86, y: 54, big: true, plus: nil,
             iceSpeed: "Fast", iceSpeedSec: "23.6s", iceCurl: "4–5", iceRec: "—",
             games: [],
             met: []),
        Stop(id: "kelowna", code: "KEL", name: "Kelowna Bonspiel", club: "Kelowna Curling Club", prov: "BC",
             dates: "JAN 9–11", record: "3–1", here: false, x: 70, y: 32, big: false, plus: "+3",
             iceSpeed: "Fast", iceSpeedSec: "24.1s", iceCurl: "5–6", iceRec: "3–1",
             games: [
                GameLine(label: "vs Carter", score: "8–4", res: "W"),
                GameLine(label: "vs Lindqvist", score: "5–7", res: "L")
            ],
             met: ["sam", "jo", "dee"]),
        Stop(id: "vernon", code: "VER", name: "Vernon Cashspiel", club: "Vernon Curling Club", prov: "BC",
             dates: "DEC 2", record: "2–1", here: false, x: 50, y: 68, big: false, plus: "+2",
             iceSpeed: "Medium", iceSpeedSec: "25.0s", iceCurl: "4–5", iceRec: "2–1",
             games: [
                GameLine(label: "vs Reid", score: "6–8", res: "L"),
                GameLine(label: "vs Mara", score: "7–5", res: "W")
            ],
             met: ["sam", "jo"]),
        Stop(id: "calgary", code: "CAL", name: "Sage Valley Open", club: "Sage Valley CC", prov: "AB",
             dates: "NOV 14–16", record: "2–2", here: false, x: 30, y: 39, big: false, plus: nil,
             iceSpeed: "Keen", iceSpeedSec: "23.2s", iceCurl: "6–7", iceRec: "2–2",
             games: [
                GameLine(label: "vs Carter", score: "9–7", res: "W"),
                GameLine(label: "vs Park", score: "4–9", res: "L")
            ],
             met: ["carter"]),
        Stop(id: "winnipeg", code: "WPG", name: "Granite City Classic", club: "Granite City CC", prov: "MB",
             dates: "OCT 24–26", record: "3–0", here: false, x: 14, y: 64, big: false, plus: nil,
             iceSpeed: "Fast", iceSpeedSec: "24.4s", iceCurl: "5–6", iceRec: "3–0",
             games: [
                GameLine(label: "vs Lindqvist", score: "6–5", res: "W"),
                GameLine(label: "vs Olsen", score: "8–3", res: "W")
            ],
             met: ["lind"])
    ]

    static let spiels: [Spiel] = [
        Spiel(id: "sp1", name: "Brier Patch Open", whereText: "Kamloops, BC", whenText: "FEB 14–16",
              status: "You're in", going: ["sam", "jo", "lind"]),
        Spiel(id: "sp2", name: "Okanagan Classic", whereText: "Kelowna, BC", whenText: "MAR 6–8",
              status: "Watching", going: ["dee", "carter"]),
        Spiel(id: "sp3", name: "Prairie Cashspiel", whereText: "Winnipeg, MB", whenText: "MAR 27–29",
              status: "Invite", going: ["lind"])
    ]

    static let feed: [Post] = [
        Post(id: "seed-1", kind: .result, author: "sam", time: "2H", body: "Took the A-final at Kelowna. Ice was lightning all weekend. 🥌", scoreFor: 8, scoreAgainst: 5, res: "WIN", vs: "vs Northern", likes: 24, comments: 6),
        Post(id: "seed-2", kind: .spiel, title: "5 curlers you follow are headed to", spielName: "Brier Patch Open", spielId: "sp1", whereText: "KAMLOOPS", whenText: "FEB 14–16", who: ["sam", "jo", "lind"]),
        Post(id: "seed-3", kind: .review, author: "jo", time: "5H", club: "Granite City CC", stars: 4, note: "fast, 5–6 ft of curl")
    ]
}
