#!/usr/bin/env node
/* ============================================================
 * gen-seed.js — single source of truth codegen.
 *
 * Reads  data/season-seed.json  (edit THIS by hand) and regenerates:
 *   1. ios/CurlPlan/Seed.generated.swift   (native seed baseline)
 *   2. the SEED block inside index.html     (web seed baseline, marker-delimited)
 *
 * Run after editing the seed:   node scripts/gen-seed.js
 * CI fails if the generated files are stale (git diff after regen).
 * This is the mechanism that keeps the iOS and web apps from drifting.
 * ============================================================ */
"use strict";
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const seedPath = path.join(root, "data", "season-seed.json");
const clubsPath = path.join(root, "data", "curling-clubs.json");
const swiftOut = path.join(root, "ios", "CurlPlan", "Seed.generated.swift");
const clubsSwiftOut = path.join(root, "ios", "CurlPlan", "Clubs.generated.swift");
const webFile = path.join(root, "index.html");

const seed = JSON.parse(fs.readFileSync(seedPath, "utf8"));
const clubsData = JSON.parse(fs.readFileSync(clubsPath, "utf8"));
// shared club vocabulary for pickers/autocomplete on both platforms
const clubSuggestions = (clubsData.clubs || [])
  .map(c => `${c.name} · ${c.city}, ${c.state}`)
  .sort();

/* ---------- Swift emit helpers ---------- */
function sstr(s) {
  return '"' + String(s == null ? "" : s).replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}
function sStrArr(arr) { return "[" + (arr || []).map(sstr).join(", ") + "]"; }
function sGameLines(arr, labelKey) {
  if (!arr || !arr.length) return "[]";
  return "[\n" + arr.map(g =>
    `                GameLine(label: ${sstr(g[labelKey])}, score: ${sstr(g.score)}, res: ${sstr(g.res)})`
  ).join(",\n") + "\n            ]";
}

function swiftCurler(c) {
  return `        Curler(id: ${sstr(c.id)}, initials: ${sstr(c.initials)}, name: ${sstr(c.name)}, role: ${sstr(c.role)}, club: ${sstr(c.club)}, prov: ${sstr(c.prov)},
               metAt: ${sstr(c.metAt)}, following: ${c.following ? "true" : "false"},
               record: ${sstr(c.stats.record)}, win: ${sstr(c.stats.win)}, clubs: ${c.stats.clubs}, mutual: ${c.stats.mutual},
               sharedClubs: ${sStrArr(c.sharedClubs)},
               form: ${sGameLines(c.form, "label")})`;
}

function swiftStop(s) {
  return `        Stop(id: ${sstr(s.id)}, code: ${sstr(s.code)}, name: ${sstr(s.name)}, club: ${sstr(s.club)}, prov: ${sstr(s.prov)},
             dates: ${sstr(s.dates)}, record: ${sstr(s.record)}, here: ${s.here ? "true" : "false"}, x: ${s.x}, y: ${s.y}, big: ${s.big ? "true" : "false"}, plus: ${s.plus ? sstr(s.plus) : "nil"},
             iceSpeed: ${sstr(s.ice.speed)}, iceSpeedSec: ${sstr(s.ice.speedSec)}, iceCurl: ${sstr(s.ice.curl)}, iceRec: ${sstr(s.ice.rec)},
             games: ${sGameLines(s.games, "opp")},
             met: ${sStrArr(s.met)})`;
}

function swiftSpiel(sp) {
  return `        Spiel(id: ${sstr(sp.id)}, name: ${sstr(sp.name)}, whereText: ${sstr(sp.where)}, whenText: ${sstr(sp.when)},
              status: ${sstr(sp.status)}, going: ${sStrArr(sp.going)})`;
}

function swiftPost(p) {
  if (p.type === "result") {
    return `        Post(id: ${sstr(p.id)}, kind: .result, author: ${sstr(p.author)}, time: ${sstr(p.time)}, body: ${sstr(p.body)}, scoreFor: ${p.score.for}, scoreAgainst: ${p.score.ag}, res: ${sstr(p.score.res)}, vs: ${sstr(p.score.vs)}, likes: ${p.likes}, comments: ${p.comments})`;
  }
  if (p.type === "spiel") {
    return `        Post(id: ${sstr(p.id)}, kind: .spiel, title: ${sstr(p.title)}, spielName: ${sstr(p.spiel)}, spielId: ${sstr(p.spielId)}, whereText: ${sstr(p.where)}, whenText: ${sstr(p.when)}, who: ${sStrArr(p.who)})`;
  }
  // review
  return `        Post(id: ${sstr(p.id)}, kind: .review, author: ${sstr(p.author)}, time: ${sstr(p.time)}, club: ${sstr(p.club)}, stars: ${p.stars}, note: ${sstr(p.note)})`;
}

const m = seed.me;
const swift = `// GENERATED by scripts/gen-seed.js from data/season-seed.json — DO NOT EDIT.
// Edit the JSON and re-run:  node scripts/gen-seed.js
import Foundation

enum Seed {
    static let me = MeInfo(
        name: ${sstr(m.name)}, initials: ${sstr(m.initials)}, role: ${sstr(m.role)},
        club: ${sstr(m.club)}, prov: ${sstr(m.prov)}, season: ${sstr(m.season)},
        stats: MeStats(clubs: ${m.stats.clubs}, prov: ${m.stats.prov}, games: ${m.stats.games}, win: ${m.stats.win}))

    static let recentStopIDs: [String] = ${sStrArr(seed.recentStops)}

    static let curlers: [Curler] = [
${seed.curlers.map(swiftCurler).join(",\n")}
    ]

    static let stops: [Stop] = [
${seed.stops.map(swiftStop).join(",\n")}
    ]

    static let spiels: [Spiel] = [
${seed.spiels.map(swiftSpiel).join(",\n")}
    ]

    static let feed: [Post] = [
${seed.feed.map(swiftPost).join(",\n")}
    ]
}
`;

fs.writeFileSync(swiftOut, swift);

/* ---------- Web emit ---------- */
// Map the canonical shape to the exact objects index.html already consumes.
const webMe = seed.me;
const webCurlers = seed.curlers.map(c => ({
  id: c.id, initials: c.initials, name: c.name, role: c.role, club: c.club, prov: c.prov,
  metAt: c.metAt, following: c.following, stats: c.stats, clubs: c.sharedClubs, form: c.form,
}));
const webStops = seed.stops; // already in web shape (ice{}, games[{opp}], met[])
const webSpiels = seed.spiels.map(sp => ({
  id: sp.id, name: sp.name, where: sp.where, when: sp.when, status: sp.status, going: sp.going,
}));
const webFeed = seed.feed.map(p => {
  if (p.type === "result") return { id: p.id, type: "result", author: p.author, time: p.time, body: p.body, score: p.score, likes: p.likes, comments: p.comments };
  if (p.type === "spiel") return { id: p.id, type: "spiel", title: p.title, spiel: p.spiel, spielId: p.spielId, where: p.where, when: p.when, who: p.who };
  return { id: p.id, type: "review", author: p.author, time: p.time, club: p.club, stars: p.stars, note: p.note };
});

const j = (v) => JSON.stringify(v, null, 2);
const webBlock =
`var defaultMe = ${j(webMe)};
var curlers = ${j(webCurlers)};
var stops = ${j(webStops)};
var recentStops = ${j(seed.recentStops)};
var feed = ${j(webFeed)};
var spiels = ${j(webSpiels)};`;

/* ---------- shared club vocabulary (from data/curling-clubs.json) ---------- */
const clubsSwift = `// GENERATED by scripts/gen-seed.js from data/curling-clubs.json — DO NOT EDIT.
import Foundation

enum Clubs {
    // "Name · City, ST" display strings for club pickers / autocomplete.
    static let all: [String] = [
${clubSuggestions.map(s => "        " + sstr(s)).join(",\n")}
    ]
}
`;
const clubsWebBlock = `var CLUB_SUGGESTIONS = ${j(clubSuggestions)};`;

function injectBlock(source, startMarker, endMarker, block, label) {
  const s = source.indexOf(startMarker);
  const e = source.indexOf(endMarker);
  if (s === -1 || e === -1) {
    console.error(`gen-seed: ${label} markers not found in index.html. Add:\n  ${startMarker}\n  ...\n  ${endMarker}`);
    process.exit(1);
  }
  return source.slice(0, s + startMarker.length) + "\n" + block + "\n" + source.slice(e);
}

const SEED_START = "/* SEED:START — generated by scripts/gen-seed.js from data/season-seed.json. DO NOT EDIT. */";
const SEED_END = "/* SEED:END */";
const CLUBS_START = "/* CLUBS:START — generated by scripts/gen-seed.js from data/curling-clubs.json. DO NOT EDIT. */";
const CLUBS_END = "/* CLUBS:END */";

const existingHtml = fs.readFileSync(webFile, "utf8");
let html = injectBlock(existingHtml, SEED_START, SEED_END, webBlock, "SEED");
html = injectBlock(html, CLUBS_START, CLUBS_END, clubsWebBlock, "CLUBS");

/* --check: fail (nonzero) if committed generated files are stale vs the data files.
   Used by CI so a data edit without a regen can never merge. */
const check = process.argv.includes("--check");
if (check) {
  const norm = (s) => s.replace(/\r\n/g, "\n");   // EOL-insensitive (Windows/Linux)
  const stale = [];
  if (norm(fs.readFileSync(swiftOut, "utf8")) !== norm(swift)) stale.push("ios/CurlPlan/Seed.generated.swift");
  if (norm(fs.readFileSync(clubsSwiftOut, "utf8")) !== norm(clubsSwift)) stale.push("ios/CurlPlan/Clubs.generated.swift");
  if (norm(existingHtml) !== norm(html)) stale.push("index.html generated block(s)");
  if (stale.length) {
    console.error("gen-seed --check: generated files are STALE. Run `node scripts/gen-seed.js` and commit.");
    stale.forEach(f => console.error("  - " + f + " out of date"));
    process.exit(1);
  }
  console.log("gen-seed --check: generated files are up to date ✓");
  process.exit(0);
}

fs.writeFileSync(swiftOut, swift);
fs.writeFileSync(clubsSwiftOut, clubsSwift);
fs.writeFileSync(webFile, html);
console.log("gen-seed: wrote " + path.relative(root, swiftOut));
console.log("gen-seed: wrote " + path.relative(root, clubsSwiftOut));
console.log("gen-seed: injected web SEED + CLUBS blocks into " + path.relative(root, webFile));
console.log(`gen-seed: ${seed.curlers.length} curlers · ${seed.stops.length} stops · ${seed.spiels.length} spiels · ${seed.feed.length} feed items · ${clubSuggestions.length} clubs`);
